### ISSUE TITLE
[Question] Cannot make HTTP request outside of coroutine

### ISSUE THREAD

**Issue by erupt321** [SinisterRectus/Discordia#162]
Currently just getting started building a bot out of discordia, not new to coding but pretty new to lua.  Running into one first issue that would love some advice to how to get around.

My main function calls another function to handle a !command.  The !command then uses the information to ask another function to make a webquery and then I chop out a url from that webpage.  I find everything fine, but my issue is using the https.request/get routines I end up with the error in title.  The error happens when I get my res.on("data",function)  and chop out my url, I'm then trying to call out another function to send it to the channel.

I did have it working at some point, but it seems like the function runs to completion while the http process runs outside of it.  Not sure what would be the best way to trigger the message -> channel once the http process is entirely complete.  Or even how to just get the http function to edit a global variable.

I'm sure it's something dumb I just haven't found yet in documents.

**Comment by Mishio595** [comment]
Discordia makes use of `coro-http` for its http capabalities, so all discordia interactions must be wrapped in a coroutine. The issue you're having on the other hand seems to arise from use of luvit's internal http module, which uses callbacks.

In order to properly assist you, we'll need to see more of what you're doing and what you're trying to accomplish. I recommend joining the discord api server (https://discord.gg/discord-api) and reaching out in `#lua-discordia` for questions about the library, or the luvit discord guild (https://discord.gg/luvit) for questions regarding luvit tools.

**Comment by erupt321** [comment]
Thanks so much, decided to just use coro-http now, took 2 seconds to rewrite it much better now, and faster.
