### ISSUE TITLE
I dont even know

### ISSUE THREAD

**Issue by TheEmerald** [SinisterRectus/Discordia#191]
I got this error:  
C:\Users\joshu\Desktop\LuaBots\AltsBot\bot.lua:2: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function 'require'
        [string "bundle:main.lua"]:118: in function 'main'
        [string "bundle:init.lua"]:49: in function <[string "bundle:init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>

Here is my code:
local discordia = require("discordia")
local client = discordia.client()

--[[
  createdAt
  timestamp
  attachment
  attachments
  author
  channel
  cleanContent
  content
  editedTimeStamp
  embed
  embeds
  guild
  link
  member
  author
]]

client:on("messageCreate", function(message)
  local content = message.content
  local member = message.member
  local memberid = message.member.id
  if content:lower() == "!ping" then
    message:reply("pong")
  end
end)

client:run("Bot "..io.open("./login.txt"):read())

**Comment by Samur3i** [comment]
It seems you've mistakenly left out the first part of the error message, which should say something like `attempt to call field 'client' (a nil value)`. As the error states, your code is failing because you're attempting to call `discordia.client()`, which does not exist.

Changing it to `discordia.Client()` should resolve the error.

**Comment by TheEmerald** [comment]
@Samur3i  That changed the error now it says this:
C:\Users\joshu\Desktop\LuaBots\AltsBot>luvit bot
2019-05-28 14:22:55 | [INFO]    | Discordia 2.6.0
2019-05-28 14:22:55 | [INFO]    | Connecting to Discord...
2019-05-28 14:22:55 | [ERROR]   | Could not authenticate, check token: ...u/Desktop/LuaBots/AltsBot/deps/secure-socket/context.lua:67: #1:TLS not supported
Maybe [SSLv3] SSLv23 TLSv1 TLSv1_1 TLSv1_2 DTLSv1 [SSLv2], option followed by _client or _server
default is TLSv1

**Comment by truemedian** [comment]
The secure-socket error is caused by a version mismatch between the OpenSSL that secure-socket expects and what newer luvit versions hold. Try both deleting deps/secure-socket and then reinstalling via `lit install luvit/secure-socket` and if that still doesn't work, reinstall luvit with the same install method from [the luvit site](https://luvit.io/install.html)

**Comment by TheEmerald** [comment]
@truemedian  that fixed a bit now it says this it is recurring to infinity

2019-05-28 18:35:10 | [INFO]    | Shard 0 : Disconnected
2019-05-28 18:35:10 | [INFO]    | Shard 0 : Reconnecting after 29221 ms...
2019-05-28 18:35:39 | [INFO]    | Shard 0 : Connected to wss://gateway.discord.gg
2019-05-28 18:35:39 | [INFO]    | Shard 0 : Received HELLO (gateway-prd-main-q9hs)
2019-05-28 18:35:39 | [WARNING] | Shard 0 : 4004 - Authentication failed.

**Comment by Mishio595** [comment]
4004 means the identification packet was malformed. Please show your code with the token redacted for privacy purposes.
