### ISSUE TITLE
TextChannel.lua:56: attempt to index local 'self' (a nil value)

### ISSUE THREAD

**Issue by Gnomorian** [SinisterRectus/Discordia#208]
> did i get here
> Uncaught Error: C:/Users/William/deps/coro-channel.lua:62: C:/Users/William/deps/discordia/libs/utils/Emitter.lua:103: .../deps/discordia/libs/containers/abstract/TextChannel.lua:56: attempt to index local 'self' (a nil value)
> stack traceback:
>         [C]: in function 'assert'
>         C:/Users/William/deps/coro-channel.lua:62: in function 'onPlain'
>         C:/Users/William/deps/secure-socket/biowrap.lua:76: in function <C:/Users/William/deps/secure-socket/biowrap.lua:61>
>         [C]: in function 'run'
>         [string "bundle:init.lua"]:52: in function <[string "bundle:init.lua"]:47>
>         [C]: in function 'xpcall'
>         [string "bundle:init.lua"]:47: in function 'fn'
>         [string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>

caused by:
```
client:on('messageCreate', function(message)
	-- lets not get caught in infinate loops checking messages from ourselves
	if message.author == guild.me.user then return end
	
	-- take the message text, parse it and pass the parameters to the relevent command function
	executeCommand(message)
	
	-- always look for these things
	print("did i get here")
	message.channel.getFirstMessage()
	print("i didnt get here")
	clearMessages(message.channel)
end)
```

**Comment by Jabbers99** [comment]
Hey,
So the issue causing that error is because you call getFirstMessage with a "." and not a ":". Also instead of getting the current user through the member of that guild, you can do client.user. Finally, this github page is for issues and bugs relating to the library and not for mistakes and getting help on how to use it. It's recommended to ask these sorts of questions in our channel (#lua-discordia) in the discord api discord. discord.gg/discord-api

**Comment by Gnomorian** [comment]
thanks, but since in the exception all the errors where coming from discordia, not my code, i assumed it was a bug, not a fault of mine. with that context, this was the best port of call.
