### ISSUE TITLE
Module Scripts not Global

### ISSUE THREAD

**Issue by superbolt999** [SinisterRectus/Discordia#240]
Currently I am trying to use a module to communicate but it is not working.
so all of these files are in the same directory
send.lua
receive.lua
Module.lua

Inside Module.lua
```lua
Module = {hi = nil}
return Module
```
Inside send.lua
```lua
local info = require("Module")
info.hi = 2
```
Inside receive.lua
```lua
local info = require("Module")
print(info.hi)-- this keeps returning nil
```

in cmd
`luvit send`
open another cmd
`luvit recieve` -- this prints out nil even if luvit send is ran first, I don't know how to fix this

**Comment by SinisterRectus** [comment]
Assuming that you are actually calling `require("Module")` instead of `require(Module)`....

You are running two independent luvit processes here. Edits made to a Lua module in one process will not be seen in another process. So when you load "recieve.lua" (spelled wrong), you are loading a new copy of the "Module.lua" without the change made in "send.lua".

**Comment by superbolt999** [comment]
oh I typed this too fast, the program runs but is there anyway I can create global variables?

**Comment by SinisterRectus** [comment]
Not in the way you are trying to use them. You would want to run this all in one process. For example, create a `main.lua` that requires and uses both the `send` and `receive` modules.

**Comment by superbolt999** [comment]
I guess that also works. Thanks
