### ISSUE TITLE
Request: Deleted channels could be moved to weak table, that's still accessible via client:getChannel()

### ISSUE THREAD

**Issue by BestMordaEver** [SinisterRectus/Discordia#242]
This might be a bit redundant, but I find it slightly counter-intuitive that deleted channel can't be accessed via `client:getChannel()` during `channelDelete` event. Currently I'm in an ugly situation where this change might help a lot.

**Comment by SinisterRectus** [comment]
Explain the situation.

**Comment by BestMordaEver** [comment]
In of itself the problem is just a series of poor design choices and the more I think about it, the less excuses I have to not just fix them. The gist of it is that my database wrapper expects exclusively channel ids, evaluates them and logs the results in context, that it pulls with `:getChannel()` (guild ids, category names etc). 
An alternative fix would be to actually just let it work with channel objects instead of ids, so it has all the required data included in it from the start

**Comment by SinisterRectus** [comment]
The point of the cache's weak table is to prevent internal duplication of a Discordia object during the course of its deletion. It is not meant to a extend the lifetime of a cached Discord object and I cannot make a guarantee that data for a deleted Discord object exists outside of the "channelDelete" event. Moving forward, I may not be able to make that guarantee at all due to gateway intents.
