### ISSUE TITLE
Way to edit embeds?

### ISSUE THREAD

**Issue by birds3345** [SinisterRectus/Discordia#248]
Is there a way to edit embeds? I can't seem to figure it out

**Comment by Bilal2453** [comment]
Sure, there is a way for editing both, embeds, and regular messages.
But since the github issues page is for "issues" only, this should go to Discordia's channel at
`discord.gg/discord-api`. There you can ask for help with Discordia.

You can also check the wiki, under the Message object to figure it out yourself.

Good luck.

**Comment by birds3345** [comment]
ah ok ty
