### ISSUE TITLE
Trying to do ban/kick system

### ISSUE THREAD

**Issue by yrahmial17** [SinisterRectus/Discordia#250]
That's half of my code, its not give really banned...

Client:on('messageCreate', function(message)
if message.content:sub(1,#"!ban") == Prefix.. "ban" then
local mentioned = message.mentionedUsers
if message.member.id == '685775752930918439' then
if #mentioned == 1 then
message.channel:send("<@!"..mentioned[1][1].."> has been banned.")
banUser(mentioned[1][1])

**Comment by yrahmial17** [comment]
Client:on('messageCreate', function(message)
    if message.content:sub(1,#"!ban") == Prefix.. "ban" then
        local mentioned = message.mentionedUsers
        if message.member.id == '685775752930918439' then
        if #mentioned == 1 then
            message.channel:send("<@!"..mentioned[1][1].."> has been banned.")
            banUser(mentioned[1][1])

            elseif #mentioned == 0 then
                message.channel:send("Error: Incorrect Syntax = !ban [user]")
            
            elseif #mentioned >= 1 then
                message.channel:send("Sorry that operation isn't supported yet.")
        end
    end
end

**Comment by Bilal2453** [comment]
Hey @yrahmial17, hope you are doing well.

That is a bit of interesting code. though you sound to be misunderstanding number of things,

1. `message.channel:send("<@!"..mentioned[1][1].."> has been banned.")`
`Message.mentionedUsers` is an [ArrayIterable](https://github.com/SinisterRectus/Discordia/wiki/ArrayIterable) object, you can't just index it using a number value. Instead you should use the `first` field (`Message.mentionedUsers.first`), or use on of the methods that can help you with picking an object up.

2. `... mentioned[1][1] ...`
`User` is an object, you also can't index that using a number value, even if you were using `mentionedUsers` correctly, you would be missing this part. I believe what you want there is the `id` field, `User.id`.

3. `banUser(mentioned[1][1])`
I am here assuming you have declared `banUser` before, and it does correspond to the desired guild, if so then the points 1, 2 also applies here, you can't index using numbers. If it is not declared, or it does not make use of the correct guild (and I am sure it doesn't) then you should be using `message.guild:banUser` instead. See [The Guild Wiki page](https://github.com/SinisterRectus/Discordia/wiki/Guild#banuserid-reason-days).

These were the things that is causing this issue, and there are some points you should be aware of as well,

1. `if message.content:sub(1,#"!ban") == Prefix.. "ban" then`
Discordia provides you string extension, which can be used here for better arguments parsing. See [The Extensions](https://github.com/SinisterRectus/Discordia/wiki/Extensions#table-stringsplitstr-delim), and [Writing Your First Bot](https://github.com/SinisterRectus/Discordia/wiki/Writing-Your-First-Bot).

2. `if #mentioned == 1 then`
There is no good reason to use this, and even if there is, you should be using `and` while having this in the previous if statement.

3. `message.channel:send("<@!"..mentioned[1][1].."> has been banned.")`
Generally it is not a good idea to hardcode the mentions syntax, use member.mentionString instead of `<@!..>`.

**Comment by SinisterRectus** [comment]
I think that's a pretty comprehensive reply. Since this issue tracker is more about problems with library code and less about problems with user code, I am going to close this and re-direct you to our support channel. Please visit #lua_discordia at https://discord.gg/discord-api.
