### ISSUE TITLE
How do i use libopus

### ISSUE THREAD

**Issue by NougatBitz** [SinisterRectus/Discordia#269]
Everytime i try to play a sound i get this error " Cannot prepare voice connection: libopus not found"
How can i download libopus...?

**Comment by truemedian** [comment]
The wiki has a topic on how to get and use voice properly.

https://github.com/SinisterRectus/Discordia/wiki/Voice

**Comment by NougatBitz** [comment]
but where do i put the ddl's???!

**Comment by Bilal2453** [comment]
Hey @NougatBitz, have you read the guide @truemedian linked? Because as far as I can tell it did indeed mention where to put the DLLs at;
> Use your current working directory if you are unsure of which to use.

"Your current working directory" means your bot's directory, the directory you are running your bot from.

Since this is not an issue nor a feature suggestion, you are better off asking for help at either [Discordia guild](https://discord.gg/EzRYYDW) or at our channel at [Discord API guild](https://discord.gg/discord-api). This issue will be closed for now.

Good luck.
