### ISSUE TITLE
luvit is not installing

### ISSUE THREAD

**Issue by YahyaAbolsaad** [SinisterRectus/Discordia#270]
When I try to install luvit it doesn't do anything, so when I use "lit" it does not work.
![image](https://user-images.githubusercontent.com/73656813/97595422-5866e480-1a0c-11eb-90c1-f21dab7824f1.png)

**Comment by Be1zebub** [comment]
why are you asking about the luvit issue in the discordia repository? ask luvit.

**Comment by Bilal2453** [comment]
Hey there, you are getting that first error ('lit' is not recognized as ...) because Luvit is not installed, when you are trying to install it though, it is giving you nothing, no errors and no success messages, my only guess there that your Anti Virus is blocking PowerShell from executing the installing script.

Either ways, since this place is for the reporting actual bugs and issues, this is the wrong place to ask, you can join our channel at [DiscordAPI](https://discord.gg/discord-api), or our Discord [Discordia](https://github.com/SinisterRectus/Discordia), so we can help you further with this issue.

Good luck.

**Comment by TGoldenB** [comment]
Please read https://luvit.io/install.html, Discordia has nothing to do with Luvit install issue. 
If you are unable to use the PowerShell and stuff, download the pre-compiled version from https://github.com/luvit/luvi/releases

Thanks.

**Comment by YahyaAbolsaad** [comment]
> Please read https://luvit.io/install.html, Discordia has nothing to do with Luvit install issue.
> If you are unable to use the PowerShell and stuff, download the pre-compiled version from https://github.com/luvit/luvi/releases
> /AND/ follow the other steps for installing Discordia.
> Thanks.

Alright, which should I install? I am using windows 10 x64 bit.
Thank you.

**Comment by YahyaAbolsaad** [comment]
> Hey there, you are getting that first error ('lit' is not recognized as ...) because Luvit is not installed, when you are trying to install it though, it is giving you nothing, no errors and no success messages, my only guess there that your Anti Virus is blocking PowerShell from executing the installing script.
> 
> Either ways, since this place is for the reporting actual bugs and issues, this is the wrong place to ask, you can join our channel at [DiscordAPI](https://discord.gg/discord-api), or our Discord [Discordia](https://github.com/SinisterRectus/Discordia), so we can help you further with this issue.
> 
> Good luck.

I disabled my antivirus and it is not working.
