### ISSUE TITLE
Document embed object.

### ISSUE THREAD

**Issue by keanuplayz** [SinisterRectus/Discordia#273]
Right now, there's no way of seeing what parameters the embed object of a message can take.
It would be handy if there was a page for it.

**Comment by Bilal2453** [comment]
Hey there, well since Discordia just sends the embed as it is, and those fields are already documented by Discord, we thought there is no need for such docs, since Discordia accepts everything Discord does (because at the end it is just passing those without even checking), therefor just looking at [this](https://discord.com/developers/docs/resources/channel#embed-object) should do the trick.

**Comment by keanuplayz** [comment]
Ah, I wasn't aware they share the exact same structure. Thanks!
