### ISSUE TITLE
Can't get private and group voice channels

### ISSUE THREAD

**Issue by heIIish** [SinisterRectus/Discordia#280]
I don't know whether I'm blind or this is just not implemented, but is there a way to get the private or group chat voice channel the Client is connected to (assuming the Client is a user account, not a bot)? I've only been able to get guild voice channels, but not any other type.

**Comment by TGoldenB** [comment]
That's against ToS, It's not allowed. Self-bot, user bot both are forbidden.

**Comment by iiRichyDev** [comment]
Creating a self-bot or user bot is against Discord's Terms of Service, which can be read [here](https://discord.com/terms).
"attempt to discover any source code, reverse engineer, decompile, disassemble, or otherwise exploit the Service "
In this case, you would be 'exploiting' the service by creating a self-bot or user bot.

**Comment by SinisterRectus** [comment]
As far as I am aware, bots can create group channels, but they cannot use them. You are limited to sending audio on guild voice channels here.
