### ISSUE TITLE
Cant figure out how to have bot say/detect custom discord emojis

### ISSUE THREAD

**Issue by DiscoLlife** [SinisterRectus/Discordia#282]
This isn't a bug or anything but I cant find anywhere else to ask, if some one has the code for a function that can do this or could help me figure this out I'd be very thankful.

local Client = discordia.Client()
function getEmoji(id)
	id = Resolver.emojiId(id)
	local guild = self._emoji_map[id]
	return guild and guild._emojis:get(id)
end

message.channel:send(Client:getEmoji(Id))
-- pretend this is in a function that activates when someone says a command, im not putting my entire code in here
what Im trying to do here is post a custom discord emoji whenever some one says the set command but this isn't working, if I turn it into a string it gives me "nil" in the chat but like this I get a bad request error

**Comment by DiscoLlife** [comment]
sorry if something is obviously wrong with what I'm doing, I'm not that good

**Comment by Bilal2453** [comment]
Hey there, for Discordia related questions please redirect your question to the [Discrodia server](https://discord.gg/EzRYYDW) or to [DAPI server](https://discord.gg/discord-api). Since this issue tracker is not meant for questions.

To answer the question though, YOU SHOULD NOT be manually initing the emoji object, instead either using the custom emojis syntax, or emoji object that already exists in a guild. For more detailed questions I hope to see you around on Discord ^^

Good luck.

**Comment by DiscoLlife** [comment]
Thank you telling me where I should be posting this, I'll be sure to go to the discord. As for your answer I'm not exactly sure on how to do that, but thanks for trying the help me!
