### ISSUE TITLE
Discord's Reply Feature

### ISSUE THREAD

**Issue by HunterAPI** [SinisterRectus/Discordia#284]
I added a table in the argument table for `message:reply(< table >)` called `message_reference` for the new Discord reply feature. It didn't work for some reason.

Edit: 
Docs https://discord.com/developers/docs/resources/channel#message-object-message-reference-structure

**Comment by object-Object** [comment]
Discordia 2.x doesn't currently support replies.

**Comment by HunterAPI** [comment]
> Discordia 2.x doesn't currently support replies. They'll be supported in 3.0.

Ah, I see. Thanks for telling me I didn't know. Do you know when 3.0 will be released?

**Comment by SinisterRectus** [comment]
The major reason why I did not add replies to 2.x is because I did not want to break the existing behavior for `message:reply(...)`, which is simply a shortcut for `message.channel:send(...)`.

There is no expected release date for 3.0 at the moment. It was previously intended to be finished in October/November 2020, but for various reasons, I have put it on hold. Now that the slash command API is (hopefully) stable, I can look into resuming work on it.
