### ISSUE TITLE
Channel:send causes repeat messages in DMs?

### ISSUE THREAD

**Issue by gideongrinberg** [SinisterRectus/Discordia#288]
I used `message.channel:send` to reply to DMs, but it causes the message to be sent over and over again (repeatedly, until the bot gets rate limited. Then it waits and starts again.) I looked at the code, and I couldn't figure out what causes this, so I thought I'd report it since it seems like a bug. `message.author:send()` works fine. If it's an intended behaviour,  a note should probably be added to the docs.

**My code:**

```lua
local discordia = require('discordia')
local client = discordia.Client()

client:on("ready", function ()
    print("Bot logged in as "..client.user.username)
end)

client:on('messageCreate', function(message)
	if message.content == '!ping' then
		message.channel:send('Pong!')
	end

    if message.guild == nil then
        message.channel:send("This is a DM!")
    end
end)

client:run(token)
```

**Comment by Bilal2453** [comment]
`messageCreate` event gets fired on any message, even if it was the bot's message you just sent itself, what's happening here is that once you send a message the bot replies, the same event gets fired again on the bot message which doesn't have a `guild` so it send a message again, then it gets triggered again because the bot just sent a message and it again checks for `guild` etc.

To fix this you should check if the message you just received owned by a bot or not, to make sure the bot doesn't reply to itself.

For more detailed answer please check [our server](https://discord.gg/EzRYYDW) or our channel at [DAPI](https://discord.gg/discord-api), since this repo's issue aren't meant for questions.

**Comment by gideongrinberg** [comment]
> `messageCreate` event gets fired on any message, even if it was the bot's message you just sent itself, what's happening here is that once you send a message the bot replies, the same event gets fired again on the bot message which doesn't have a `guild` so it send a message again, then it gets triggered again because the bot just sent a message and it again checks for `guild` etc.
> 
> To fix this you should check if the message you just received owned by a bot or not, to make sure the bot doesn't reply to itself.
> 
> For more detailed answer please check [our server](https://discord.gg/EzRYYDW) or our channel at [DAPI](https://discord.gg/discord-api), since this repo's issue aren't meant for questions.

I realized my mistake right before you sent this, sorry about that!

**Comment by gideongrinberg** [comment]
Thanks for your help!
