### ISSUE TITLE
Getting a guild based on guild id

### ISSUE THREAD

**Issue by FFranker** [SinisterRectus/Discordia#334]
I'm trying to get a specific guild with guild id.
I have tried this so far but it seems to be ineffective;

for guild in pairs(client.guilds.cache) do
print(guild.name)
end

**Comment by object-Object** [comment]
You're looking for `client:getGuild(id)`, documented [here](https://github.com/SinisterRectus/Discordia/wiki/Client#getguildid). Also, the best way to get help with your code is to join the [Discord API](https://discord.gg/discord-api) or [Discordia](https://discord.gg/sinisterware) servers, rather than opening an issue on GitHub.

**Comment by FFranker** [comment]
Alright thanks.
