### ISSUE TITLE
400 bad request when trying to ban?

### ISSUE THREAD

**Issue by 3x71us1v3** [SinisterRectus/Discordia#337]
I don't know why this would be happening.
Code:
`local membertoban = message1.guild:getMember(grantId)`
 `local ban = membertoban.guild:banUser(membertoban.user, "grant", 64)`

**Comment by object-Object** [comment]
As documented on the [Guild](https://github.com/SinisterRectus/Discordia/wiki/Guild#banuserid-reason-days) page, the third argument of `guild:banUser`, `days`, must be between 0 and 7. Also, the best way to get help with your code is to join the [Discord API](https://discord.gg/discord-api) or [Discordia](https://discord.gg/sinisterware) servers, rather than opening an issue on GitHub.

**Comment by 3x71us1v3** [comment]
Oh, I see. Thank you :)
