### ISSUE TITLE
False error with invalid token

### ISSUE THREAD

**Issue by VADemon** [SinisterRectus/Discordia#34]
I used the "Client Secret:" instead of "App bot user token" and it kept showing me the _"Disconnected from gateway unexpectedly, Attemping to reconnect after 1000 ms..."_ error.

This error is not self-explainable in this case.

1) Provide the HTTP response as console output
2) Basic warning at init if the given "token" doesn't seem to be a real token.

**Comment by PurgePJ** [comment]
Client Secret is not supposed to be used as a token.

**Comment by PurgePJ** [comment]
Thinking I've come up with a simple solution (for now).

https://github.com/SinisterRectus/Discordia/blob/master/discordia/client/Socket.lua#L61

We could check the length of token and if it's under... let's say 50 (mine is 59) then print that it's not a valid token, Client secret's length is 37.

**Comment by SinisterRectus** [comment]
The token is first used in a handshake via WebSocket, so there is no regular HTTP response like you would expect for other API methods. Because most users don't have difficulty providing a valid token, I never bothered to embellish the result of using an invalid token. I can look into changing this in the future, though.

**Comment by SinisterRectus** [comment]
Token handling has been improved as of commit 97affb4f5e055d48d9b9234d0f97820bee3a78dd. An error is thrown if an invalid token is provided.
