### ISSUE TITLE
Running example code, and getting error 403.

### ISSUE THREAD

**Issue by Misteridze** [SinisterRectus/Discordia#341]
Hi, I ran Discordia's template code, and any time when I say !ping, it says:
`[ERROR]   | 403 - Forbidden : POST https://discord.com/api/v7/channels/blahblahblah`
What do I do?

**Comment by callmehSpear** [comment]
Well... blah blah isn't a channel or guild ID, is it?

**Comment by object-Object** [comment]
If the template code is unmodified except for adding the token, check and see if the bot has permission to send messages in the channel you ran the command in. Also, the best way to get help with your code is to join the [Discord API](https://discord.gg/discord-api) or [Discordia](https://discord.gg/sinisterware) servers, rather than opening an issue on GitHub.

**Comment by Misteridze** [comment]
> If the template code is unmodified except for adding the token, check and see if the bot has permission to send messages in the channel you ran the command in. Also, the best way to get help with your code is to join the [Discord API](https://discord.gg/discord-api) or [Discordia](https://discord.gg/sinisterware) servers, rather than opening an issue on GitHub.

Yes, i gave bot perms

**Comment by object-Object** [comment]
Can you please join one of the servers I linked? It'll be easier to troubleshoot there.
