### ISSUE TITLE
403 - Forbidden : PUT error when trying to ban a member

### ISSUE THREAD

**Issue by exatron2300** [SinisterRectus/Discordia#375]
I have a 403 error when im trying to ban a member. Here is the error and here is my script:
![image](https://user-images.githubusercontent.com/125516395/219712838-ba9b7103-59ae-4099-bfd6-f974412fc705.png)
![image](https://user-images.githubusercontent.com/125516395/219712885-9306bcc6-81a1-4c63-88ca-9525218a46c2.png)

**Comment by broman** [comment]
Does your bot have permission to ban members?

**Comment by exatron2300** [comment]
> Does your bot have permission to ban members

the oauth2 gives the bot all of the permissions, even tho it doesnt have a ban perms role

**Comment by SinisterRectus** [comment]
I don't think that code corresponds to the error you are seeing.

`message.author.tag` will never be equal to `exatron23#` so the code will never run.
You're iterating over every guild member and for some reason are indexing each member with a random number, which is undefined and impossibly a member that you are somehow attempting to ban...

Please visit https://discord.gg/sinisterware since this is not a library issue.
