### ISSUE TITLE
You should introduce a enumeration system.

### ISSUE THREAD

**Issue by HuddaFire** [SinisterRectus/Discordia#46]
It would make things very easier, such as switching the client user's status.
**Example:** discordia.Enums.UserStatusType.DoNotDisturb
**Example 2:** discordia.Enums.UserMembershipType.Nitro
**Example 3:** discordia.Enums.UserMembershipType.Partner

Well, I guess there isn't much things you can apply Enums to in Discord. I think custom enums are useful in some situations.

**Comment by SinisterRectus** [comment]
Enums have floated on and off my todo list since before version 1.0. They would probably keep some features cleaner, but since Lua doesn't have any built-in enum support, I handle most enumerablesby just accepting strings as arguments:

For example:

```lua
role:hasPermission("sendMessages")
-- versus
role:hasPermission(discordia.enums.sendMessages)
```

There are certainly better places to use them, though, like the ones you mention or channel types or message types. I don't expect to add enums soon, but I definitely would like to in the future

**Comment by HuddaFire** [comment]
Alright.

**Comment by LoganDark** [comment]
Since everything is stringly typed the enums could simply hold the strings.

**Comment by SinisterRectus** [comment]
Discordia 2.0 has been released. This uses special enumerations to represent the many numerical values that the Discord API provides.
