### ISSUE TITLE
Discord API Deprecation

### ISSUE THREAD

**Issue by JaredMFProgramming** [SinisterRectus/Discordia#58]
Discord API and Gateway versions 3, 4, and 5 are deprecated, and will be discontinued on October 16th.

There is Discord API and Gateway version 6.  Have you considered updating the Discord API version on this library to 6?

**Comment by Tigerism** [comment]
This library will use Gateway version 6 with Discordia 2.0. Release is soon™

**Comment by JaredMFProgramming** [comment]
Okay.  I hope Discord 2.0 comes soon. 😉

Sent from Mail for Windows 10

**Comment by SinisterRectus** [comment]
Updating the current generation of Discordia to use gateway v6 is possible, but not easy, so I haven't done it. Instead, I've switched to the new gateway in Discordia 2.0, which is still in development.

I do plan to get this released before the change-over so that people have time to update their bots. If, for some reason, I cannot meet the deadline, I will implement v6 into the current version of Discordia.

You can follow the development on its [branch](https://github.com/SinisterRectus/Discordia/tree/2.0) or [project page](https://github.com/SinisterRectus/Discordia/projects/1).

One way or another, it will be supported. We can leave this open until it is.

**Comment by SinisterRectus** [comment]
Discordia 2.0, which uses gateway v6, has been released. Updating is recommended.
